name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      # ── Checkout repository ───────────────────────────
      - uses: actions/checkout@v4

      # ── Node / Hardhat tests ──────────────────────────
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install JS deps & run Hardhat tests
        run: |
          npm ci
          npx hardhat compile
          npx hardhat test --network hardhat

      # ── Go vet inside bridge/ ─────────────────────────
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: go vet
        working-directory: bridge
        run: go vet .

      # ── Python PCA smoke test ─────────────────────────
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run PCA script
        run: |
          pip install -r analysis/requirements.txt
          python analysis/pca_analysis.py